package com.example.backend.dto.financials;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public record ExpenseSnapshotResponse(
    long version,
    LocalDate payPeriodStart,
    LocalDate payPeriodEnd,
    LocalDate currentDate,
    FinancialPlanningSettingsResponse planningSettings,
    FinancialProjectionRolesResponse projectionRoles,
    BigDecimal totalMonthlyExpenses,
    BigDecimal paidTotal,
    BigDecimal unpaidTotal,
    BigDecimal payPeriodTotal,
    BigDecimal totalAnnualWithdrawals,
    BigDecimal annualPayPeriodTotal,
    BigDecimal totalTrackedAssets,
    BigDecimal totalDebt,
    BigDecimal netWorth,
    List<AssetCategoryResponse> assetCategories,
    List<DebtAccountResponse> debtAccounts,
    List<IncomeSummaryItemResponse> incomeSummaryItems,
    List<ExpenseBillResponse> bills,
    List<AnnualWithdrawalResponse> annualWithdrawals,
    List<IncomeEventResponse> incomeEvents,
    List<ImportantDateResponse> importantDates) {

  public ExpenseSnapshotResponse(
      long version,
      LocalDate payPeriodStart,
      LocalDate payPeriodEnd,
      FinancialProjectionRolesResponse projectionRoles,
      BigDecimal totalMonthlyExpenses,
      BigDecimal paidTotal,
      BigDecimal unpaidTotal,
      BigDecimal payPeriodTotal,
      BigDecimal totalAnnualWithdrawals,
      BigDecimal annualPayPeriodTotal,
      BigDecimal totalTrackedAssets,
      BigDecimal totalDebt,
      BigDecimal netWorth,
      List<AssetCategoryResponse> assetCategories,
      List<DebtAccountResponse> debtAccounts,
      List<IncomeSummaryItemResponse> incomeSummaryItems,
      List<ExpenseBillResponse> bills,
      List<AnnualWithdrawalResponse> annualWithdrawals,
      List<IncomeEventResponse> incomeEvents,
      List<ImportantDateResponse> importantDates) {
    this(
        version,
        payPeriodStart,
        payPeriodEnd,
        payPeriodStart,
        null,
        projectionRoles,
        totalMonthlyExpenses,
        paidTotal,
        unpaidTotal,
        payPeriodTotal,
        totalAnnualWithdrawals,
        annualPayPeriodTotal,
        totalTrackedAssets,
        totalDebt,
        netWorth,
        assetCategories,
        debtAccounts,
        incomeSummaryItems,
        bills,
        annualWithdrawals,
        incomeEvents,
        importantDates);
  }

  public ExpenseSnapshotResponse(
      long version,
      LocalDate payPeriodStart,
      LocalDate payPeriodEnd,
      BigDecimal totalMonthlyExpenses,
      BigDecimal paidTotal,
      BigDecimal unpaidTotal,
      BigDecimal payPeriodTotal,
      BigDecimal totalAnnualWithdrawals,
      BigDecimal annualPayPeriodTotal,
      BigDecimal totalTrackedAssets,
      BigDecimal totalDebt,
      BigDecimal netWorth,
      List<AssetCategoryResponse> assetCategories,
      List<DebtAccountResponse> debtAccounts,
      List<IncomeSummaryItemResponse> incomeSummaryItems,
      List<ExpenseBillResponse> bills,
      List<AnnualWithdrawalResponse> annualWithdrawals,
      List<IncomeEventResponse> incomeEvents,
      List<ImportantDateResponse> importantDates) {
    this(
        version,
        payPeriodStart,
        payPeriodEnd,
        payPeriodStart,
        null,
        null,
        totalMonthlyExpenses,
        paidTotal,
        unpaidTotal,
        payPeriodTotal,
        totalAnnualWithdrawals,
        annualPayPeriodTotal,
        totalTrackedAssets,
        totalDebt,
        netWorth,
        assetCategories,
        debtAccounts,
        incomeSummaryItems,
        bills,
        annualWithdrawals,
        incomeEvents,
        importantDates);
  }
}
